workflows:
  default:
    name: React Native Workflow
    environment:
      node: 16 # Specify the Node.js version
    scripts:
      - name: Debug repository structure
        script: |
          echo "Current directory:"
          pwd
          echo "Directory structure:"
          ls -R
      - name: Debug codemagic directory
        script: |
          echo "Contents of codemagic directory:"
          ls codemagic || echo "codemagic directory not found"
      - name: Install dependencies
        script: |
          cd codemagictest
          yarn install
      - name: Run tests
        script: |
          cd codemagictest
          yarn test
      - name: Build the app
        script: |
          cd codemagictest/android && ./gradlew assembleRelease
    artifacts:
      - codemagictest/android/app/build/outputs/**/*