workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        
    environment:
        android_signing:
            - myKeystore
        vars:
        PACKAGE_NAME: "io.codemagic.sample.reactnative"