workflows:

  react-native-android:

    name: React Native Android

    max_build_duration: 120

    instance_type: mac_mini_m2

    environment:

      android_signing:

        - myKeystore

      groups:

        - google_play

      vars:

        PACKAGE_NAME: "io.codemagic.sample.reactnative"

    scripts:

      - name: Set Android SDK location

        script: | 

          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Install npm dependencies

        script: | 

          cd codemagictest

          npm install

      - name: Run Expo Prebuild

        script: | 

          npx expo prebuild

      - name: Set up app/build.gradle

        script: | 

          mv ./support-files/build.gradle android/app

      - name: Build Android release

        script: | 

          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")

          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
          

              UPDATED_BUILD_NUMBER=$BUILD_NUMBER

          else

              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))

          fi

          cd android

          ./gradlew bundleRelease \

            -PversionCode=$UPDATED_BUILD_NUMBER \

            -PversionName=1.0.$UPDATED_BUILD_NUMBER

    artifacts:

      - android/app/build/outputs/**/*.aab

    publishing:

      email:

        recipients:

          - t3hije01@students.oamk.fi

        notify:

          success: true

          failure: false

      google_play:

        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS

        track: internal

        submit_as_draft: true