workflows:
  default:
    name: React Native Workflow
    environment:
      node: 16 # Specify the Node.js version
    scripts:
      - name: Debug repository structure
        script: |
          echo "Current directory:"
          pwd
          echo "Directory structure:"
          ls -R
      - name: Install dependencies
        script: |
          cd codemagic/codemagictest
          yarn install
      - name: Run tests
        script: |
          cd codemagic/codemagictest
          yarn test
      - name: Build the app
        script: |
          cd codemagic/codemagictest/android && ./gradlew assembleRelease
    artifacts:
      - codemagic/codemagictest/android/app/build/outputs/**/*