workflows:
  default:
    name: React Native Workflow
    environment:
      node: 16 # Specify the Node.js version
      yarn: true # Use Yarn as the package manager
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Run tests
        script: yarn test
      - name: Build the app
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*