workflows:
  default:
    name: React Native Workflow
    environment:
      node: 16 # Specify the Node.js version
    scripts:
      - name: Debug repository structure
        script: ls -R # Print the directory structure for debugging
      - name: Install dependencies
        script: |
          cd codemagictest
          yarn install
      - name: Run tests
        script: |
          cd codemagictest
          cd __tests__
          yarn test
      - name: Build the app
        script: |
          cd codemagictest/android && ./gradlew assembleRelease
    artifacts:
      - codemagictest/android/app/build/outputs/**/*