workflows:
  default:
    name: React Native Workflow
    environment:
      node: 16 # Specify the Node.js version
    scripts:
      - name: Debug repository structure
        script: |
          echo "Current directory:"
          pwd
          echo "Complete directory tree:"
          find . -print
      - name: Debug key files and directories
        script: |
          echo "Searching for android directory:"
          find . -type d -name "android" || echo "android directory not found"
          echo "Searching for build.gradle file:"
          find . -type f -name "build.gradle" || echo "build.gradle file not found"
          echo "Searching for app/build.gradle file:"
          find . -type f -name "build.gradle" -path "*/app/*" || echo "app/build.gradle file not found"
          echo "Searching for package.json file:"
          find . -type f -name "package.json" || echo "package.json file not found"
          echo "Searching for node_modules directory:"
          find . -type d -name "node_modules" || echo "node_modules directory not found"
          echo "Searching for yarn.lock file:"
          find . -type f -name "yarn.lock" || echo "yarn.lock file not found"
      - name: Verify codemagictest directory
        script: |
          echo "Contents of codemagictest directory:"
          ls codemagictest || echo "codemagictest directory not found"
          echo "Verifying package.json in codemagictest:"
          if [ -f codemagictest/package.json ]; then
            echo "package.json found in codemagictest"
          else
            echo "package.json not found in codemagictest"
          fi
      - name: Install dependencies
        script: |
          echo "Navigating to codemagictest directory..."
          cd codemagictest
          echo "Current directory after navigation:"
          pwd
          echo "Contents of current directory:"
          ls
          if [ ! -f "package.json" ]; then
            echo "package.json not found in codemagictest directory"
            exit 1
          fi
          echo "Installing dependencies in codemagictest"
          yarn install
      - name: Build the app
        script: |
          ANDROID_DIR=$(find . -type d -name "android" | head -n 1)
          if [ -z "$ANDROID_DIR" ]; then
            echo "Android directory not found"
            echo "Attempting to locate app/build.gradle instead..."
            ANDROID_DIR=$(find . -type f -name "build.gradle" -path "*/app/*" | xargs -n1 dirname | head -n 1)
          fi
          if [ -z "$ANDROID_DIR" ]; then
            echo "Android project directory not found"
            exit 1
          fi
          echo "Building app in $ANDROID_DIR"
          cd "$ANDROID_DIR" && ./gradlew assembleRelease
    artifacts:
      - codemagictest/android/app/build/outputs/**/*