workflows:
  default:
    name: React Native Workflow
    environment:
      node: 16 # Specify the Node.js version
    scripts:
      - name: Install dependencies
        script: |
          cd app
          yarn install
      - name: Run tests
        script: |
          cd app
          yarn test
      - name: Build the app
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*